---
output: 
 html_document:
   theme: readable
   highlight: tango
---

<style>
.main-container {
 max-width: 900px !important;
 margin-left: auto;
 margin-right: auto;
 padding: 2em;
}
h2 {
 text-align: center;
 color: #2c3e50;
 margin-top: 2em;
 margin-bottom: 1em;
}
p {
 text-align: justify;
 line-height: 1.6;
 margin-bottom: 1.5em;
}
</style>

## Personal Projects

The following bookdown is a small collection of basic codes that can be used as a baseline when to approach machine learning projects. This was put together in my third year of my undergraduate degree. [Personal ML Baseline](https://simonraymond2003.github.io/MachineLearning/)

## Publications, Working Papers and Research in Progress

- Myself and Dr. Nick Manuel are currently looking to publish a refined version of [Fourth Downs Decoded (PDF)](https://library2.smu.ca/handle/01/9003/browse?type=author&value=Raymond%2C+Simon).

- Third author for a more advanced version of [Non-exporter to Exporter: Making the Shift](https://craftalliance.ca/wp-content/uploads/2025/10/Report_NonExporterToExporter.pdf) with Dr. Ron Kalafsky and Dr. Mark Raymond.

- Currently working on a paper to explore momentum in 9-ball billards. 



